[tool.poetry]
name = "reptile"
version = "0.1.0"
description = ""
authors = ["dyfly0227@gmail.com"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
selenium = "^4.16.0"
requests = "^2.31.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

